name: Build and Test on Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build_And_Test_Logs_To_File:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Visual Studio latest
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 'latest'

      - name: Compile Demo Programs
        run: |
          cd examples
          g++.exe demo1.cpp -o demo1.exe -lole32
          g++.exe demo2.cpp -o demo2.exe -lole32
          g++.exe demo3.cpp -o demo3.exe -lole32
          g++.exe demo4.cpp -o demo4.exe -lole32
          g++.exe demo5.cpp -o demo5.exe -lole32

      - name: Check if demo.exe exists
        run: |
          $logPath = "logs/BuildTest.log"
          mkdir -p logs
          if (Test-Path "examples\\demo1.exe") {
            Write-Host "Compilation successful, demo1.exe found. Run." | Out-File -FilePath $logPath -Append
          } else {
            Write-Host "Compilation failed, demo1.exe not found." | Out-File -FilePath $logPath -Append
            exit 1
          }
          
          if (Test-Path "examples\\demo2.exe") {
            Write-Host "Compilation successful, demo2.exe found. Run." | Out-File -FilePath $logPath -Append
          } else {
            Write-Host "Compilation failed, demo2.exe not found." | Out-File -FilePath $logPath -Append
            exit 1
          }
        
          if (Test-Path "examples\\demo3.exe") {
            Write-Host "Compilation successful, demo3.exe found. Run." | Out-File -FilePath $logPath -Append
          } else {
            Write-Host "Compilation failed, demo3.exe not found." | Out-File -FilePath $logPath -Append
            exit 1
          }

          if (Test-Path "examples\\demo4.exe") {
            Write-Host "Compilation successful, demo4.exe found. Run." | Out-File -FilePath $logPath -Append
          } else {
            Write-Host "Compilation failed, demo4.exe not found." | Out-File -FilePath $logPath -Append
            exit 1
          }

          if (Test-Path "examples\\demo5.exe") {
            Write-Host "Compilation Successful, demo5.exe found. Run." | Out-File -FilePath $logPath -Append
          } else {
            Write-Host "demo5.exe not found." | Out-File -FilePath $logPath -Append
          }

      - name: Run Demo
        run: |
          cd examples
          .\demo1.exe
          .\demo2.exe
          .\demo3.exe
          .\demo4.exe
          .\demo5.exe

      - name: Save Logs
        run: |
          $logPath = "logs/BuildTest.log"
          Write-Host "Logs saved to $logPath" | Out-File -FilePath $logPath -Append
  test_job:
    runs-on: windows-latest
    steps:
      - name: TEST
        run: |
          echo TEST
      - name: TEST2
        run: |
          echo Logs>nul
      