name: Build and Test on Windows

on:
  push:
    branches:
      - master  # 可以根据需要修改为其他分支名
  pull_request:
    branches:
      - master  # 对于 PR 也可以触发测试

jobs:
  Build_And_Test_Logs_To_File:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Visual Studio latest
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 'latest'

      - name: Compile Demo Programs
        run: |
          cd examples
          g++.exe demo1.cpp -o demo1.exe -lole32
          g++.exe demo2.cpp -o demo2.exe -lole32
          g++.exe demo3.cpp -o demo3.exe -lole32
          g++.exe demo4.cpp -o demo4.exe -lole32

      - name: Check if demo.exe exists
        run: |
          if (Test-Path "examples\\demo1.exe") {
            Write-Host "Compilation successful, demo1.exe found. Run."
          } else {
            Write-Host "Compilation failed, demo1.exe not found."
            Save-Transcript -Path "logs/BuildTest.log" -Force
            exit 1
          }
          
          if (Test-Path "examples\\demo2.exe") {
            Write-Host "Compilation successful, demo2.exe found. Run."
          } else {
            Write-Host "Compilation failed, demo2.exe not found."
            Save-Transcript -Path "logs/BuildTest.log" -Force
            exit 1
          }
        
          if (Test-Path "examples\\demo3.exe") {
            Write-Host "Compilation successful, demo3.exe found. Run."
          } else {
            Write-Host "Compilation failed, demo3.exe not found."
            Save-Transcript -Path "logs/BuildTest.log" -Force
            exit 1
          }

          if (Test-Path "examples\\demo4.exe") {
            Write-Host "Compilation successful, demo4.exe found. Run."
          } else {
            Write-Host "Compilation failed, demo4.exe not found."
            Save-Transcript -Path "logs/BuildTest.log" -Force
            exit 1
          }

      - name: Run Demo
        run: |
          cd examples
          .\demo1.exe
          .\demo2.exe
          .\demo3.exe
          .\demo4.exe

      - name: Save Logs
        run : |
            mkdir -p logs
            Save-Transcript -Path "logs/BuildTest.log" -Force